name = "Flat"
license = "MIT"
licenselink = "Link to theme's license"
description = "A theme with light color and multi-section support"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/theArcLabs/flat-arc/"

tags = ["blog", "personal", "light", "dark", "responsive"]
features = []

# If the theme has multiple authors
#authors = [
#  {name = "", homepage = ""},
#]

# If the theme has a single author
[author]
    name = "thepettypow"
    homepage = "https://github.com/thepettypow/"

# If porting an existing theme
#[original]
#    author = "Name of original author"
#    homepage = "His/Her website"
#    repo = "Link to source code of original theme"
