title = "Flat theme"
theme = "flat-arc"
themesDir = "../.."
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 4
baseURL = ""

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4

[params]
description = "Example site for hugo-theme-flat"
mainSections = ['posts']

## uncomment belows and set proper values to enable remark42
# [params.remark42]
# host=''
# site_id=''
# max_shown_comments=100
# theme='light'
# locale='en'
# show_email_subscription=false
# simple_view=true


# you can set multi row of footers like these
[[params.footer_rows]]
[[params.footer_rows.items]]
name = "ARC LABS"
url = "https://arclabs.com"


[[menus.main]]
name = "Posts"
url = "/posts/"
weight = 30

[[menus.main]]
name = "Essays"
url = "/essays/"
weight = 40

[[menus.main]]
pageref = "about"
name = "About"
weight = 80

# 2-level sub menus are supported
[[menus.main]]
name = "Services"
weight = 60
[[menus.main]]
parent = "Services"
name = "Service A"
url = "#"
[[menus.main]]
parent = "Services"
name = "Service B"
url = "#"
